spring:
  application:
    name: fruitable
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3307/fruitable
    username: root
    password: r1r2r3
    hikari:
      connection-init-sql: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4 
logging:
  level:
    '[com.shop.fruitable.mapper]' : TRACE
  
server:
  port: 8005
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30